steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/seanchas-cloud/homework-driveback:$REVISION_ID", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/seanchas-cloud/homework-driveback:$REVISION_ID"]
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - "set"
  - "image"
  - "deployment/homework-driveback"
  - "homework-container=gcr.io/seanchas-cloud/homework-driveback:$REVISION_ID"
  env:
  - "CLOUDSDK_COMPUTE_ZONE=us-east4-b"
  - "CLOUDSDK_CONTAINER_CLUSTER=homework-driveback-cluster"
