steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/seanchas-cloud/homework-driveback:$SHORT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/seanchas-cloud/homework-driveback:$SHORT_SHA"]
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - "set"
  - "image"
  - "deployment/homework-driveback"
  - "homework-container=gcr.io/seanchas-cloud/homework-driveback:$SHORT_SHA"
  env:
  - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
  - "CLOUDSDK_CONTAINER_CLUSTER=homework-driveback-cluster"
